name: Deployment

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Lint
      run: npm run lint 

    - name: Generate bot config
      run: 'npm run botConfig "${bot_key}" "${db_url}"'
      env:
        bot_key: ${{ secrets.BOT_KEY }}
        db_url: ${{ secrets.DB_STRING }}

    - name: Deployment
      run: |
        mkdir -p ~/.ssh
        echo "${deploy_key}" > ~/.ssh/deploy_key
        chmod 600 ~/.ssh/deploy_key
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key krishna@sidmani.com 'systemctl --user stop ProblemsBot && rm -rf /home/krishna/ProblemsBot'
        rsync -avr -e 'ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no' . krishna@sidmani.com:/home/krishna/ProblemsBot
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key krishna@sidmani.com 'systemctl --user start ProblemsBot'
      env:
        deploy_key: ${{ secrets.DEPLOY_KEY }}
